name: Lint
on:
  workflow_dispatch: {}
  pull_request:
    branches: [master]
jobs:
  lint:
    name: Run golangci-lint
    if: github.event.pull_request.user.login != 'renovate-bot'
    runs-on: nas
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run golangci-lint
        uses: https://github.com/reviewdog/action-golangci-lint@v2.10
        env:
          REVIEWDOG_GITEA_API_TOKEN: ${{ secrets.LINT_TOKEN }}
          GITEA_ADDRESS: ${{vars.API_ADDRESS}}
        with:
          reporter: gitea-pr-review
          cache: false
          level: warning
          golangci_lint_flags: --timeout=1m
